### ISSUE TITLE
Create documentation for Catalog Services And Geoprice services

### ISSUE THREAD

**Issue by yogi-bp** [ByPrice/byprice-public-api-docs#11]
Just retailer product

**Comment by yogi-bp** [comment]
@ExpoAshique  Please make sure it works fine with our partner key
1) 
https://github.com/ByPrice/byprice-public-api-docs/blob/master/catalog-services/retailer_product.md

2) https://github.com/ByPrice/byprice-public-api-docs/blob/master/geoprice-services/retailer_price.md

**Comment by ExpoPythonist** [comment]
SHARE FZKEYs on Server

**Comment by ExpoPythonist** [comment]
RETAILER Product Issue Found:
+===================================+
1. I got some error on "retailer_product/add"  Like "(psycopg2.errors.DatatypeMismatch) column \"special_requirement\" is of type jsonb but expression is of type text[]\nLINE 1: ..."
2. "retailer_product/update"  If the product not found We are getting wrong error message

**Comment by ExpoPythonist** [comment]
1. All retailer product works perfectly
2. retailer_product/update returning correct message now

**Comment by ExpoPythonist** [comment]
This Issue Seems Okay with me. Approved
